kind: pipeline
name: default

steps:
  - name: test
    image: haggaie/symbiyosys:latest
    commands:
      - apt-get update && apt-get install -y make curl git
      - cd formal
      - make verif;
